[package]
name = "atk_mod_rm"
version = "0.1.0"
authors = ["paddywwof <support@eldwick.org.uk>"]

[lib]
name = "atk_mod_rm"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.7.0"
ndarray = "0.13"

[dependencies.pyo3]
version = "0.8"
features = ["extension-module"]